-- 0066_halo_saw_that_seed.sql
-- Content pool for the fire-and-forget "Halo Saw That" reaction toast.
-- Hooked into achievements.ts:unlockAchievement() — see that file for the trigger.

insert into public.halo_lines (moment_type, text) values
  ('halo_saw_that', 'Not bad at all. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo noticed. Keep that energy up.'),
  ('halo_saw_that', 'Halo noticed. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Huh. Nice. Keep that energy up.'),
  ('halo_saw_that', 'Halo saw that one. Chillverse remembers moments like this.'),
  ('halo_saw_that', 'Halo''s watching. That''s the kind of move Halo likes.'),
  ('halo_saw_that', 'Halo''s paying attention. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Well, well. Don''t stop now.'),
  ('halo_saw_that', 'Halo clocked that. Halo''s keeping score.'),
  ('halo_saw_that', 'Huh. Nice. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo''s been keeping an eye on you. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Look at you go. Not everyone pulls that off.'),
  ('halo_saw_that', 'Halo caught that. You''re on a roll today.'),
  ('halo_saw_that', 'Impressive. That''s the kind of move Halo likes.'),
  ('halo_saw_that', 'Not bad at all. You''re on a roll today.'),
  ('halo_saw_that', 'Look at you go. Chillverse remembers moments like this.'),
  ('halo_saw_that', 'Halo''s impressed. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo''s watching. Chillverse remembers moments like this.'),
  ('halo_saw_that', 'Okay, that was smooth. Keep that energy up.'),
  ('halo_saw_that', 'That was a moment. Someone''s leveling up fast.'),
  ('halo_saw_that', 'Halo''s taking notes. You just made this more interesting.'),
  ('halo_saw_that', 'Okay, that was smooth. You''re on a roll today.'),
  ('halo_saw_that', 'Halo noticed. You just made this more interesting.'),
  ('halo_saw_that', 'Halo saw that one. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo''s taking notes. Not everyone pulls that off.'),
  ('halo_saw_that', 'Halo''s paying attention. You''re on a roll today.'),
  ('halo_saw_that', 'Halo''s watching. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Impressive. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo caught that. Someone''s leveling up fast.'),
  ('halo_saw_that', 'Halo''s been keeping an eye on you. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo''s taking notes. Don''t stop now.'),
  ('halo_saw_that', 'Impressive. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Huh. Nice. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Okay, that was smooth. Chillverse remembers moments like this.'),
  ('halo_saw_that', 'Well, well. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Halo raised an eyebrow. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo clocked that. Don''t stop now.'),
  ('halo_saw_that', 'That was a moment. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo''s paying attention. Someone''s leveling up fast.'),
  ('halo_saw_that', 'Halo''s watching. Someone''s leveling up fast.'),
  ('halo_saw_that', 'That was a moment. You just made this more interesting.'),
  ('halo_saw_that', 'Halo clocked that. That''s worth bragging about.'),
  ('halo_saw_that', 'Impressive. Not everyone pulls that off.'),
  ('halo_saw_that', 'Halo caught that. Not everyone pulls that off.'),
  ('halo_saw_that', 'Halo''s watching. Not everyone pulls that off.'),
  ('halo_saw_that', 'Halo raised an eyebrow. Halo''s keeping score.'),
  ('halo_saw_that', 'Okay, that was smooth. Don''t stop now.'),
  ('halo_saw_that', 'That didn''t go unnoticed. You just made this more interesting.'),
  ('halo_saw_that', 'Halo''s watching. Don''t stop now.'),
  ('halo_saw_that', 'Look at you go. Don''t stop now.'),
  ('halo_saw_that', 'Halo clocked that. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'Halo caught that. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'That was a moment. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'That didn''t go unnoticed. That''s the kind of move Halo likes.'),
  ('halo_saw_that', 'Not bad at all. Chillverse remembers moments like this.'),
  ('halo_saw_that', 'Halo''s impressed. Someone''s leveling up fast.'),
  ('halo_saw_that', 'Not bad at all. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Halo''s been keeping an eye on you. Don''t stop now.'),
  ('halo_saw_that', 'Halo''s been keeping an eye on you. Not everyone pulls that off.'),
  ('halo_saw_that', 'Halo raised an eyebrow. Someone''s leveling up fast.'),
  ('halo_saw_that', 'Halo saw that one. Halo''s keeping score.'),
  ('halo_saw_that', 'Look at you go. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Halo noticed. You''re on a roll today.'),
  ('halo_saw_that', 'Well, well. That''s the kind of move Halo likes.'),
  ('halo_saw_that', 'That didn''t go unnoticed. Halo''s keeping score.'),
  ('halo_saw_that', 'Look at you go. That''s the kind of move Halo likes.'),
  ('halo_saw_that', 'Halo clocked that. Chillverse remembers moments like this.'),
  ('halo_saw_that', 'Halo''s taking notes. Halo''s keeping score.'),
  ('halo_saw_that', 'Huh. Nice. Chillverse remembers moments like this.'),
  ('halo_saw_that', 'Halo noticed. Don''t stop now.'),
  ('halo_saw_that', 'Well, well. Keep that energy up.'),
  ('halo_saw_that', 'Halo saw that one. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Halo''s been keeping an eye on you. Halo''s keeping score.'),
  ('halo_saw_that', 'Not bad at all. Not everyone pulls that off.'),
  ('halo_saw_that', 'Halo noticed. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Halo''s watching. Keep that energy up.'),
  ('halo_saw_that', 'That didn''t go unnoticed. Don''t stop now.'),
  ('halo_saw_that', 'Look at you go. That''s worth bragging about.'),
  ('halo_saw_that', 'Halo''s impressed. You''re on a roll today.'),
  ('halo_saw_that', 'Halo''s paying attention. Don''t stop now.'),
  ('halo_saw_that', 'Look at you go. Keep that energy up.'),
  ('halo_saw_that', 'Halo clocked that. That''s the kind of move Halo likes.'),
  ('halo_saw_that', 'Well, well. Not everyone pulls that off.'),
  ('halo_saw_that', 'That was a moment. You''re on a roll today.'),
  ('halo_saw_that', 'Halo clocked that. Someone''s leveling up fast.'),
  ('halo_saw_that', 'Halo noticed. That''s the kind of move Halo likes.'),
  ('halo_saw_that', 'Halo''s paying attention. Keep that energy up.'),
  ('halo_saw_that', 'That didn''t go unnoticed. Keep that energy up.'),
  ('halo_saw_that', 'Huh. Nice. Halo''s keeping score.'),
  ('halo_saw_that', 'Halo raised an eyebrow. Not everyone pulls that off.'),
  ('halo_saw_that', 'Not bad at all. Halo''s keeping score.'),
  ('halo_saw_that', 'Halo caught that. That''s the kind of move Halo likes.'),
  ('halo_saw_that', 'Halo raised an eyebrow. That''s worth bragging about.'),
  ('halo_saw_that', 'That was a moment. Don''t stop now.'),
  ('halo_saw_that', 'Okay, that was smooth. Halo''s keeping score.'),
  ('halo_saw_that', 'Halo''s taking notes. That one''s going in the highlight reel.'),
  ('halo_saw_that', 'Okay, that was smooth. Not everyone pulls that off.'),
  ('halo_saw_that', 'Okay, that was smooth. Halo''s quietly rooting for you.'),
  ('halo_saw_that', 'That didn''t go unnoticed. That''s worth bragging about.'),
  ('halo_saw_that', 'Halo''s taking notes. Someone''s leveling up fast.');
