-- 0070_halo_random_surprise_seed.sql
-- Content pool for the Random Surprise Popup (plan §4.6).

insert into public.halo_lines (moment_type, text) values
  ('random_surprise', 'Halo felt like dropping by. Consider this a little thank-you.'),
  ('random_surprise', 'Halo popped in. Consider this a little thank-you.'),
  ('random_surprise', 'Halo felt like dropping by. A little something before Halo vanishes again.'),
  ('random_surprise', 'Halo felt like dropping by. Small gift, no strings.'),
  ('random_surprise', 'Look who showed up. You earned a little extra today.'),
  ('random_surprise', 'Halo swooped in. Don''t read too much into it. Or do.'),
  ('random_surprise', 'Halo''s here. A little something before Halo vanishes again.'),
  ('random_surprise', 'Halo drifted by. Halo likes surprising the regulars.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. Just because.'),
  ('random_surprise', 'Halo just showed up. Don''t read too much into it. Or do.'),
  ('random_surprise', 'A little Halo magic. Enjoy the moment.'),
  ('random_surprise', 'Halo''s here. Consider this a little thank-you.'),
  ('random_surprise', 'Surprise — it''s Halo. Just because.'),
  ('random_surprise', 'Surprise — it''s Halo. Enjoy the moment.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. Take it and keep going.'),
  ('random_surprise', 'Halo just showed up. For sticking around.'),
  ('random_surprise', 'Halo popped in. Take it and keep going.'),
  ('random_surprise', 'Halo just showed up. Halo likes surprising the regulars.'),
  ('random_surprise', 'Surprise — it''s Halo. No reason. Well, one reason.'),
  ('random_surprise', 'Halo drifted by. Just because.'),
  ('random_surprise', 'Surprise — it''s Halo. For sticking around.'),
  ('random_surprise', 'Look who showed up. Enjoy the moment.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. Enjoy the moment.'),
  ('random_surprise', 'Look who showed up. Chillverse likes to keep you on your toes.'),
  ('random_surprise', 'Halo drifted by. Take it and keep going.'),
  ('random_surprise', 'A flicker, and Halo''s here. Consider this a little thank-you.'),
  ('random_surprise', 'Surprise — it''s Halo. Take it and keep going.'),
  ('random_surprise', 'A flicker, and Halo''s here. Halo likes surprising the regulars.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. You earned a little extra today.'),
  ('random_surprise', 'A little Halo magic. Small gift, no strings.'),
  ('random_surprise', 'Halo''s got something for you. Chillverse likes to keep you on your toes.'),
  ('random_surprise', 'Halo popped in. Small gift, no strings.'),
  ('random_surprise', 'Out of the blue, Halo''s here. A little something before Halo vanishes again.'),
  ('random_surprise', 'Out of the blue, Halo''s here. Small gift, no strings.'),
  ('random_surprise', 'Halo swooped in. A little something before Halo vanishes again.'),
  ('random_surprise', 'Halo popped in. Enjoy the moment.'),
  ('random_surprise', 'Halo swooped in. Take it and keep going.'),
  ('random_surprise', 'Halo drifted by. You earned a little extra today.'),
  ('random_surprise', 'A little Halo magic. A little something before Halo vanishes again.'),
  ('random_surprise', 'Halo''s got something for you. You earned a little extra today.'),
  ('random_surprise', 'Look who showed up. No reason. Well, one reason.'),
  ('random_surprise', 'Out of the blue, Halo''s here. Halo likes surprising the regulars.'),
  ('random_surprise', 'Halo drifted by. Small gift, no strings.'),
  ('random_surprise', 'Halo swooped in. Halo likes surprising the regulars.'),
  ('random_surprise', 'Surprise — it''s Halo. Chillverse likes to keep you on your toes.'),
  ('random_surprise', 'Halo swooped in. Consider this a little thank-you.'),
  ('random_surprise', 'Halo''s here. You earned a little extra today.'),
  ('random_surprise', 'Out of the blue, Halo''s here. No reason. Well, one reason.'),
  ('random_surprise', 'Halo swooped in. Small gift, no strings.'),
  ('random_surprise', 'Halo drifted by. A little something before Halo vanishes again.'),
  ('random_surprise', 'Halo felt like dropping by. No reason. Well, one reason.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. Halo likes surprising the regulars.'),
  ('random_surprise', 'Halo''s here. For sticking around.'),
  ('random_surprise', 'Look who showed up. For sticking around.'),
  ('random_surprise', 'Halo drifted by. Enjoy the moment.'),
  ('random_surprise', 'Halo popped in. Don''t read too much into it. Or do.'),
  ('random_surprise', 'Halo''s here. No reason. Well, one reason.'),
  ('random_surprise', 'Look who showed up. A little something before Halo vanishes again.'),
  ('random_surprise', 'A flicker, and Halo''s here. Chillverse likes to keep you on your toes.'),
  ('random_surprise', 'Halo just showed up. Enjoy the moment.'),
  ('random_surprise', 'A flicker, and Halo''s here. Don''t read too much into it. Or do.'),
  ('random_surprise', 'Halo swooped in. No reason. Well, one reason.'),
  ('random_surprise', 'Out of the blue, Halo''s here. Just because.'),
  ('random_surprise', 'Halo''s here. Small gift, no strings.'),
  ('random_surprise', 'Halo felt like dropping by. Enjoy the moment.'),
  ('random_surprise', 'Halo''s got something for you. Don''t read too much into it. Or do.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. Chillverse likes to keep you on your toes.'),
  ('random_surprise', 'Halo''s here. Enjoy the moment.'),
  ('random_surprise', 'Out of the blue, Halo''s here. For sticking around.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. For sticking around.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. Don''t read too much into it. Or do.'),
  ('random_surprise', 'Halo swooped in. Just because.'),
  ('random_surprise', 'Halo just showed up. Just because.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. No reason. Well, one reason.'),
  ('random_surprise', 'Halo''s got something for you. A little something before Halo vanishes again.'),
  ('random_surprise', 'Halo''s got something for you. Consider this a little thank-you.'),
  ('random_surprise', 'Surprise — it''s Halo. A little something before Halo vanishes again.'),
  ('random_surprise', 'Surprise — it''s Halo. Don''t read too much into it. Or do.'),
  ('random_surprise', 'Out of nowhere, Halo appears. You earned a little extra today.'),
  ('random_surprise', 'A little Halo magic. Take it and keep going.'),
  ('random_surprise', 'Halo couldn''t resist stopping by. Consider this a little thank-you.'),
  ('random_surprise', 'Out of nowhere, Halo appears. Enjoy the moment.'),
  ('random_surprise', 'A flicker, and Halo''s here. Take it and keep going.'),
  ('random_surprise', 'Look who showed up. Consider this a little thank-you.'),
  ('random_surprise', 'Halo just showed up. Small gift, no strings.'),
  ('random_surprise', 'Out of the blue, Halo''s here. Chillverse likes to keep you on your toes.'),
  ('random_surprise', 'Halo felt like dropping by. Take it and keep going.'),
  ('random_surprise', 'Out of nowhere, Halo appears. No reason. Well, one reason.'),
  ('random_surprise', 'Out of the blue, Halo''s here. Enjoy the moment.'),
  ('random_surprise', 'Halo popped in. No reason. Well, one reason.'),
  ('random_surprise', 'A flicker, and Halo''s here. Just because.'),
  ('random_surprise', 'A flicker, and Halo''s here. No reason. Well, one reason.'),
  ('random_surprise', 'Halo''s here. Don''t read too much into it. Or do.'),
  ('random_surprise', 'A little Halo magic. For sticking around.'),
  ('random_surprise', 'Halo felt like dropping by. Chillverse likes to keep you on your toes.'),
  ('random_surprise', 'Halo''s got something for you. For sticking around.'),
  ('random_surprise', 'Halo felt like dropping by. Just because.'),
  ('random_surprise', 'A flicker, and Halo''s here. Small gift, no strings.'),
  ('random_surprise', 'Look who showed up. Just because.'),
  ('random_surprise', 'Halo popped in. Chillverse likes to keep you on your toes.');
